-- Data Kalender Pendidikan SDN 2 Nangerang 2026-2027

INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Awal Semester', 'holiday', '2026-07-01', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Awal Semester', 'holiday', '2026-07-06', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Masa Pengenalan Lingkungan Sekolah', 'other', '2026-07-13', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Jadi Purwakarta', 'holiday', '2026-07-20', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Pramuka / Pahlawan', 'other', '2026-08-14', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2026-08-17', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2026-08-25', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Peringatan Hari Besar Islam', 'holiday', '2026-08-28', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Udara Bersih', 'other', '2026-09-07', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Bambu Sedunia', 'other', '2026-09-18', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Sumatif Tengah Semester', 'deadline', '2026-09-21', 1, '#F59E0B', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Kesaktian Pancasila', 'other', '2026-10-01', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Sumpah Pemuda', 'other', '2026-10-28', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Pramuka / Pahlawan', 'other', '2026-11-10', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Guru Nasional dan HUT PGRI', 'other', '2026-11-25', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Disabilitas Internasional', 'other', '2026-12-03', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Anti Korupsi', 'other', '2026-12-09', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Sumatif Akhir Semester', 'deadline', '2026-12-14', 1, '#F59E0B', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Tanggal Penetapan Rapot', 'deadline', '2026-12-21', 1, '#F59E0B', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Pembagian Rapot', 'other', '2026-12-23', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2026-12-24', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Peringatan Hari Besar Islam', 'holiday', '2026-12-25', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2026-12-28', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-01-01', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-01-04', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-02-07', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Awal Ramadhan', 'holiday', '2027-02-08', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Pesantren Kilat', 'training', '2027-02-17', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Pesantren Kilat', 'training', '2027-02-22', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Pesantren Kilat', 'training', '2027-02-29', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Pesantren Kilat', 'training', '2027-03-01', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Simulasi', 'other', '2027-03-04', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-03-08', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Idul Fitri', 'holiday', '2027-03-09', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('HAS', 'other', '2027-03-22', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-03-26', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Buruh', 'holiday', '2027-04-22', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Bambu Sedunia', 'other', '2027-04-23', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('TKA Susulan', 'deadline', '2027-04-26', 1, '#F59E0B', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-05-01', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-05-06', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Asesmen Sumatif Akhir Jenjang', 'deadline', '2027-05-10', 1, '#F59E0B', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('IA', 'other', '2027-05-17', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-05-20', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('OSN', 'other', '2027-05-24', 1, '#10B981', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Nasional', 'holiday', '2027-06-01', 1, '#EF4444', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Hari Lingkungan Hidup', 'other', '2027-06-05', 1, '#3B82F6', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Asesmen Sumatif Akhir Tahun', 'deadline', '2027-06-07', 1, '#F59E0B', 1);
INSERT OR IGNORE INTO calendar_events (title, event_type, start_date, is_all_day, color, created_by) VALUES ('Libur Akhir Tahun', 'holiday', '2027-06-28', 1, '#EF4444', 1);