import { beforeEach, afterEach, describe, it, expect, vi } from 'vitest';
import { webcrypto } from 'node:crypto';
const mocks = vi.hoisted(() => ({ api: vi.fn(), stream: vi.fn(), providers: [{ slug: 'api', name: 'API kelas', configured: 1 }, { slug: 'gemini-flash', name: 'Gemini', configured: 0 }] }));
vi.mock('../public/static/js/api.js', async original => ({ ...await original<any>(), api: mocks.api }));
vi.mock('../public/static/js/ai-stream.js', async original => ({ ...await original<any>(), streamPost: mocks.stream }));
let studio: any, monitor: any, appState: any;
beforeEach(async () => {
  vi.resetModules(); vi.stubGlobal('crypto', webcrypto); localStorage.clear();
  document.body.innerHTML = '<div id="app"><main id="main-content" data-feature-page="slide"></main></div>';
  appState = (await import('../public/static/js/state.js')).state;
  appState.user = { id: 91, nama: 'Guru uji', role: 'user' }; appState.currentPage = 'slide';
  mocks.api.mockReset().mockResolvedValue({ success: true, data: mocks.providers }); mocks.stream.mockReset();
  studio = await import('../public/static/js/pages/slide.js'); monitor = await import('../public/static/js/ai-live-monitor.js');
  document.querySelector('#main-content')!.innerHTML = studio.renderSlide(); studio.initSlide();
  await vi.waitFor(() => expect(document.querySelector<HTMLSelectElement>('#sg-model-select')!.value).toBe('api'));
});
afterEach(() => { document.querySelector<HTMLButtonElement>('#monitor-dismiss-btn')?.click(); vi.unstubAllGlobals(); vi.restoreAllMocks(); document.body.innerHTML = ''; });
describe('Teacher-facing Slide workflow', () => {
  it('saves an unfinished brief and keeps template selection independent of model status', async () => {
    const topic = document.querySelector<HTMLTextAreaElement>('[name="topik"]')!;
    topic.value = 'Siklus air di lingkungan sekolah'; topic.dispatchEvent(new Event('input', { bubbles: true }));
    await vi.waitFor(() => expect(JSON.parse(localStorage.getItem('kkg_slide_studio_v2_91')!).config.topik).toBe(topic.value));
    document.querySelector<HTMLFormElement>('#sg-brief-form')!.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await vi.waitFor(() => expect(document.querySelector('#sg-model-status')!.textContent).toContain('Model yang dipilih'));
    document.querySelector<HTMLButtonElement>('[data-template="jelajah-ipas"]')!.click();
    expect(document.querySelector('#sg-design-summary')!.textContent).toContain('Jelajah IPAS');
    expect(document.querySelector('#sg-model-status')!.textContent).toContain('Model yang dipilih');
    expect(document.querySelector<HTMLSelectElement>('#sg-model-select')!.value).toBe('api');
  });
  it('sends the displayed model and complete brief even when the teacher never changes the model dropdown', async () => {
    const deck = (await import('../public/static/js/slides/examples.js')).exampleDeck();
    mocks.stream.mockImplementation(async (_url, _data, onEvent) => { onEvent('done', { data: deck }); });
    const form = document.querySelector<HTMLFormElement>('#sg-brief-form')!;
    (form.elements.namedItem('topik') as HTMLTextAreaElement).value = 'Pecahan dengan kertas lipat';
    (form.elements.namedItem('jenjangKelas') as HTMLSelectElement).value = 'Kelas 3';
    expect(form.elements.namedItem('tujuanPembelajaran')).toBeNull();
    expect(form.textContent).not.toContain('Tujuan belajar');
    (form.elements.namedItem('extraInstructions') as HTMLTextAreaElement).value = 'Tanpa alat digital';
    form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await vi.waitFor(() => expect(document.querySelector<HTMLSelectElement>('#sg-model-select')!.value).toBe('api'));
    document.querySelector<HTMLButtonElement>('#sg-generate')!.click(); document.querySelector<HTMLButtonElement>('#sg-generate')!.click();
    await vi.waitFor(() => expect(mocks.stream).toHaveBeenCalledTimes(1));
    expect(mocks.stream.mock.calls[0][1]).toMatchObject({ aiProvider: 'api', jenjangKelas: 'Kelas 3', extraInstructions: 'Tanpa alat digital' });
    expect(mocks.stream.mock.calls[0][1]).not.toHaveProperty('tujuanPembelajaran');
    expect(mocks.stream.mock.calls[0][3]).toMatchObject({ signal: expect.any(AbortSignal), jobId: expect.any(String) });
    await vi.waitFor(() => expect(document.querySelector<HTMLButtonElement>('#monitor-review-btn')!.hidden).toBe(false));
    document.querySelector<HTMLButtonElement>('#monitor-review-btn')!.click();
    await vi.waitFor(() => expect(document.querySelector('#sg-slide-render-area svg')).not.toBeNull());
    expect(document.querySelector('#sg-save-status')!.textContent).toContain('tersimpan di perangkat ini');
  });
  it('keeps a layout-warning draft editable and blocks export only until the marked text is fixed', async () => {
    const deck = (await import('../public/static/js/slides/examples.js')).exampleDeck();
    deck.slides[4].quizExplanation = 'Pembahasan yang perlu diringkas. '.repeat(35).trim();
    deck.meta = { quality: { readyForExport: false, layoutWarnings: ['Slide 5: pembahasan terlalu panjang untuk bidang teks.'] } } as any;
    mocks.stream.mockImplementation(async (_url, _data, onEvent) => { onEvent('done', { data: deck }); });
    const form = document.querySelector<HTMLFormElement>('#sg-brief-form')!;
    (form.elements.namedItem('topik') as HTMLTextAreaElement).value = 'Pecahan di kelas';
    form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await vi.waitFor(() => expect(document.querySelector<HTMLSelectElement>('#sg-model-select')!.value).toBe('api'));
    document.querySelector<HTMLButtonElement>('#sg-generate')!.click();
    await vi.waitFor(() => expect(document.querySelector<HTMLButtonElement>('#monitor-review-btn')!.hidden).toBe(false));
    expect(document.querySelector('#monitor-message')!.textContent).toContain('Rapikan bidang teks');
    document.querySelector<HTMLButtonElement>('#monitor-review-btn')!.click();
    await vi.waitFor(() => expect(document.querySelector('#sg-quality')!.textContent).toContain('Slide 5'));
    const { exportScenes } = await import('../public/static/js/slides/export.js');
    expect(() => exportScenes((window as any).slideGenState.deck, 'matematika-visual', { aspectRatio: '16:9' })).toThrow('Perbaiki slide');
    document.querySelector<HTMLButtonElement>('[data-slide="4"]')!.click();
    const explanation = document.querySelector<HTMLTextAreaElement>('[data-field="quizExplanation"]')!;
    expect(explanation.value).toBe(deck.slides[4].quizExplanation);
    explanation.value = 'Tiga dari empat bagian sama besar diwarnai.'; explanation.dispatchEvent(new Event('input', { bubbles: true }));
    expect(document.querySelector('#sg-quality')!.textContent).toContain('sudah diperiksa');
    expect(exportScenes((window as any).slideGenState.deck, 'matematika-visual', { aspectRatio: '16:9' })).toHaveLength(8);
    expect(mocks.stream).toHaveBeenCalledOnce();
  });
  it('offers an incomplete draft for review and preserves editable material instead of terminating the job', async () => {
    const deck = (await import('../public/static/js/slides/examples.js')).exampleDeck();
    deck.slides[1].layout = 'content'; deck.slides[1].content = []; deck.slides[1].visual = undefined;
    deck.meta = { requestedSlideCount: 8, quality: { partial: true, contentIssues: ['Slide 2: Tambahkan konsep inti yang akan dipelajari.'], layoutWarnings: [] } } as any;
    mocks.stream.mockImplementation(async (_url, _data, onEvent) => { onEvent('done', { partial: true, data: deck }); });
    const form = document.querySelector<HTMLFormElement>('#sg-brief-form')!;
    (form.elements.namedItem('topik') as HTMLTextAreaElement).value = 'Bentuk di sekitar kita';
    form.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true }));
    await vi.waitFor(() => expect(document.querySelector<HTMLSelectElement>('#sg-model-select')!.value).toBe('api'));
    document.querySelector<HTMLButtonElement>('#sg-generate')!.click();
    await vi.waitFor(() => expect(document.querySelector('#monitor-review-btn')!.textContent).toContain('parsial'));
    expect(document.querySelector('#monitor-message')!.textContent).toContain('Lengkapi slide');
    document.querySelector<HTMLButtonElement>('#monitor-review-btn')!.click();
    await vi.waitFor(() => expect(document.querySelector('#sg-quality')!.textContent).toContain('Slide 2'));
    const { exportScenes } = await import('../public/static/js/slides/export.js');
    expect(() => exportScenes((window as any).slideGenState.deck, 'matematika-visual', { aspectRatio: '16:9' })).toThrow();
    document.querySelector<HTMLButtonElement>('[data-slide="1"]')!.click();
    const content = document.querySelector<HTMLTextAreaElement>('[data-field="content"]')!;
    content.value = 'Pecahan menyatakan bagian dari satu keseluruhan.'; content.dispatchEvent(new Event('input', { bubbles: true }));
    expect(exportScenes((window as any).slideGenState.deck, 'matematika-visual', { aspectRatio: '16:9' })).toHaveLength(8);
    expect(mocks.stream).toHaveBeenCalledOnce();
  });
  it('keeps sample quiz answers hidden, then reveals them only on teacher action and saves edits', async () => {
    document.querySelector<HTMLButtonElement>('#sg-example')!.click();
    document.querySelector<HTMLButtonElement>('[data-slide="4"]')!.click();
    expect(document.querySelector('#sg-slide-render-area')!.textContent).not.toContain('Pembilang menunjukkan');
    document.querySelector<HTMLButtonElement>('#sg-reveal')!.click();
    expect(document.querySelector('#sg-slide-render-area')!.textContent).toContain('Pembilang menunjukkan');
    const title = document.querySelector<HTMLInputElement>('[data-field="title"]')!; title.value = 'Latihan pecahan'; title.dispatchEvent(new Event('input', { bubbles: true }));
    await vi.waitFor(() => expect(JSON.parse(localStorage.getItem('kkg_slide_studio_v2_91')!).deck.slides[4].title).toBe('Latihan pecahan'));
  });
  it('marks an unavailable model as unavailable and disables AI creation while keeping examples usable', async () => {
    mocks.api.mockResolvedValue({ success: true, data: [{ slug: 'gemini', name: 'Gemini', configured: 0 }] });
    document.querySelector<HTMLButtonElement>('#sg-reload-model')!.click();
    await vi.waitFor(() => expect(document.querySelector('#sg-model-status')!.textContent).toContain('Belum ada model siap pakai'));
    expect(document.querySelector<HTMLButtonElement>('#sg-outline')!.disabled).toBe(true);
    expect(document.querySelector<HTMLButtonElement>('#sg-example')!.disabled).toBe(false);
  });
  it('does not restore a removed objectives field from an older saved brief', async () => {
    appState.user = { ...appState.user, id: 92 };
    localStorage.setItem('kkg_slide_studio_v2_92', JSON.stringify({ version: 2, config: { topik: 'Bentuk di rumah', tujuanPembelajaran: 'Tujuan lama', tujuan_pembelajaran: 'Tujuan lama lain' }, deck: { slides: [] } }));
    document.querySelector('#main-content')!.innerHTML = studio.renderSlide(); studio.initSlide();
    expect(document.querySelector('[name="tujuanPembelajaran"]')).toBeNull();
    expect((window as any).slideGenState.config).not.toHaveProperty('tujuanPembelajaran');
    expect((window as any).slideGenState.config).not.toHaveProperty('tujuan_pembelajaran');
    expect((window as any).slideGenState.config.topik).toBe('Bentuk di rumah');
  });
  it('round-trips a saved version through the real archive drawer and restores its original edited content', async () => {
    document.querySelector<HTMLButtonElement>('#sg-example')!.click();
    const title = document.querySelector<HTMLInputElement>('[data-field="title"]')!;
    title.value = 'Versi untuk kelas tiga'; title.dispatchEvent(new Event('input', { bubbles: true }));
    document.querySelector<HTMLButtonElement>('#sg-save-archive')!.click();
    title.value = 'Edit setelah arsip'; title.dispatchEvent(new Event('input', { bubbles: true }));
    document.querySelector<HTMLButtonElement>('#sg-history')!.click();
    expect(document.querySelector('#kkg-archive-drawer-root')!.textContent).toContain('Riwayat Slide');
    expect(document.querySelectorAll('.btn-open-archive')).toHaveLength(1);
    document.querySelector<HTMLButtonElement>('.btn-open-archive')!.click();
    expect(document.querySelector<HTMLInputElement>('[data-field="title"]')!.value).toBe('Versi untuk kelas tiga');
    expect(document.querySelector('#kkg-archive-drawer-root')).toBeNull();
  });
});
